services:

  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - mydbv:/var/lib/mysql
    networks:
      - my-app

  wordpress:
    image: wordpress:php8.4-fpm
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - myhtmlv:/var/www/html
    networks:
      - my-app

  nginx:
    image: nginx:1.28.0-alpine
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - 8090:80
    volumes:
      - myhtmlv:/var/www/html
      - /home/u21/Downloads/dockersss/2/4/nginx-conf.d:/etc/nginx/conf.d
    networks:
      - my-app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8081:80
    networks:
      - my-app

volumes:
  myhtmlv:
  mydbv:

networks:
  my-app:
    driver: bridge
