version: '3.9'

services:
  grafana:
    image: grafana/grafana:10.2.4
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
  prometheus:
    image: bitnami/prometheus:2.50.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
