version: '3.1'
services:

  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: user1
      MYSQL_PASSWORD: wpass123
      MYSQL_ROOT_PASSWORD: rootpass000

  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - 8094:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user1
      WORDPRESS_DB_PASSWORD: wpass123
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
  db:

# короче ошибка что контейнер DB падает. скорее всего -v db:/var/lib/mysql
# docker run -d --name db        -v db:/var/lib/mysql                  -e MYSQL_DATABASE=wpdb    -e MYSQL_USER=user1        -e MYSQL_PASSWORD=wpass123        -e MYSQL_ROOT_PASSWORD=1 mysql
# или
# docker run -d --name db                                              -e MYSQL_DATABASE=wpdb    -e MYSQL_USER=user1        -e MYSQL_PASSWORD=wpass123        -e MYSQL_ROOT_PASSWORD=1 mysql

# docker run -d --name wordpress -v wordpress:/var/www/html -p 8094:80 -e WORDPRESS_DB_NAME=wpdb -e WORDPRESS_DB_USER=user1 -e WORDPRESS_DB_PASSWORD=wpass123 -e WORDPRESS_DB_HOST=db --link db:db wordpress
