version: '3.9'
services:

# ok
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user1
      WORDPRESS_DB_PASSWORD: pass123
      WORDPRESS_DB_NAME: wpdb
    depends_on:
      - db
    volumes:
      - html:/var/www/html
    networks:
      - azrael-app

# ok
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass123
      MYSQL_ROOT_PASSWORD: root_pass-000
    volumes:
      - db:/var/lib/mysql
    networks:
      - azrael-app

# ok
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8081:80
    networks:
      - azrael-app

volumes:
  html:
  db:

networks:
  azrael-app:
    driver: bridge
